# Generated by Django 3.2.7 on 2021-09-14 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import thumbs.models.models_image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('use_source_img', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThumbRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(null=True, upload_to=thumbs.models.models_image.user_dir_path)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbs', to='thumbs.userimage')),
                ('thumb_rule', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='thumbs.thumbrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThumbUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thumbs.thumbplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumb_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='thumbplan',
            name='thumb_rules',
            field=models.ManyToManyField(to='thumbs.ThumbRule'),
        ),
        migrations.CreateModel(
            name='ImageTempLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thumbs.userimage')),
            ],
        ),
    ]
