# Generated by Django 3.2.7 on 2021-09-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbrule',
            name='width',
        ),
        migrations.AlterField(
            model_name='thumbrule',
            name='height',
            field=models.IntegerField(unique=True),
        ),
    ]
