# Generated by Django 3.2.7 on 2021-09-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbplan',
            name='use_expiring_links',
            field=models.BooleanField(default=False),
        ),
    ]
