# Generated by Django 3.2.7 on 2021-09-13 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thumbs', '0002_auto_20210913_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumb_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
