# Generated by Django 3.2.7 on 2021-09-13 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thumbs', '0003_alter_thumbuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagethumb',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbs', to='thumbs.userimage'),
        ),
    ]
