# Generated by Django 3.2.7 on 2021-09-14 14:35

from django.db import migrations, models
import thumbs.models.models_image


class Migration(migrations.Migration):

    dependencies = [
        ('thumbs', '0004_alter_imagethumb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTempLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.CharField(max_length=255)),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='userimage',
            name='file',
            field=models.ImageField(null=True, upload_to=thumbs.models.models_image.user_dir_path),
        ),
    ]
